
-- Create V_DASHBOARD
CREATE OR REPLACE VIEW SEMANTIC.V_DASHBOARD AS
SELECT STATUS, LINE_OF_BUSINESS, REGION,
COUNT(*) AS TOTAL_POLICIES,
SUM(PREMIUM_AMOUNT) AS TOTAL_PREMIUM,
AVG(PREMIUM_AMOUNT) AS AVG_PREMIUM
FROM DWH.FACT_POLICIES
GROUP BY STATUS, LINE_OF_BUSINESS, REGION;
