CREATE OR REPLACE TABLE CURATED.POLICY_SUMMARY AS
SELECT
    STATUS,
    LINE_OF_BUSINESS,
    REGION,

    COUNT(*) AS TOTAL_POLICIES,
    SUM(PREMIUM_AMOUNT) AS TOTAL_PREMIUM,

    SUM(CASE WHEN FLAGGED_FOR_REVIEW = TRUE THEN 1 ELSE 0 END) AS FLAGGED_COUNT,

    SUM(CASE 
            WHEN EXPIRY_DATE <= DATEADD(DAY,30,CURRENT_DATE) 
            THEN 1 ELSE 0 
        END) AS EXPIRING_SOON_COUNT

FROM CURATED.POLICIES_ENRICHED
GROUP BY STATUS, LINE_OF_BUSINESS, REGION;