CREATE OR REPLACE TABLE CURATED.POLICIES_ENRICHED AS
SELECT
    ID,
    POLICY_NUMBER,
    POLICYHOLDER_NAME,
    LINE_OF_BUSINESS,
    STATUS,
    PREMIUM_AMOUNT,
    CURRENCY,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    REGION,
    UNDERWRITER,
    FLAGGED_FOR_REVIEW,
    CREATED_AT,
    UPDATED_AT,

    -- ✅ Derived columns (VERY IMPORTANT)
    CASE 
        WHEN PREMIUM_AMOUNT > 1000000 THEN 'HIGH'
        WHEN PREMIUM_AMOUNT > 250000 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL,

    CASE 
        WHEN EXPIRY_DATE <= DATEADD(DAY, 30, CURRENT_DATE) THEN 'EXPIRING_SOON'
        ELSE 'NORMAL'
    END AS EXPIRY_STATUS

FROM RAW.POLICIES;
