-- RAW.POLICIES
CREATE OR REPLACE TABLE RAW.POLICIES (
 ID STRING, POLICY_NUMBER STRING, POLICYHOLDER_NAME STRING,
 LINE_OF_BUSINESS STRING, STATUS STRING, PREMIUM_AMOUNT NUMBER(12,2),
 CURRENCY STRING, EFFECTIVE_DATE DATE, EXPIRY_DATE DATE, REGION STRING,
 UNDERWRITER STRING, FLAGGED_FOR_REVIEW BOOLEAN DEFAULT FALSE,
 CREATED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
);