CREATE OR REPLACE TABLE DWH.DIM_CUSTOMER AS
SELECT DISTINCT
    POLICYHOLDER_NAME AS CUSTOMER_NAME
FROM CURATED.POLICIES_ENRICHED;

CREATE OR REPLACE TABLE DWH.DIM_REGION AS
SELECT DISTINCT
    REGION
FROM CURATED.POLICIES_ENRICHED;