CREATE OR REPLACE TABLE DWH.FACT_POLICIES AS
SELECT
    ID,
    POLICY_NUMBER,
    PREMIUM_AMOUNT,
    RISK_LEVEL,
    STATUS,
    LINE_OF_BUSINESS,
    REGION,
    UNDERWRITER,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM CURATED.POLICIES_ENRICHED;